### ISSUE TITLE
Winner Screen is not opening

### ISSUE THREAD

**Issue by rahulsain** [GetStream/stream-draw-android#2]
guest user type correct answer still in host, the game doesn't finish as in host side, the NewChatMessage doesn't update with guest message. Only with host message it is getting updated

@skydoves

**Comment by skydoves** [comment]
Hey @rahulsain, you must ensure you're using the right Stream Chat SDK API on your [dashboard](https://getstream.io/dashboard/).

**Comment by rahulsain** [comment]
@skydoves can you verfiy from your end that winner screen is opening or not by using latest commit to this repo?

**Comment by rahulsain** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/50570677/223759500-77095e9f-5c11-43a6-96ef-66ec07830220.png">
fixed the issue
